"""add last_checked_at to websites

Revision ID: 7e91c20b139b
Revises: 0be6efb8a1e6
Create Date: 2026-06-30 01:37:51.452350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e91c20b139b'
down_revision: Union[str, None] = '0be6efb8a1e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websites', sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('websites', 'last_checked_at')
    # ### end Alembic commands ###