"""add current_status to websites

Revision ID: aaec7de223cc
Revises: bb99f45db452
Create Date: 2026-06-30 03:03:55.753856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaec7de223cc'
down_revision: Union[str, None] = 'bb99f45db452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websites', sa.Column('current_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('websites', 'current_status')
    # ### end Alembic commands ###